server:
  port: 8000

zuul:
  prefix: /api
  routes:
    user-service:
      path: /user/**
      url: http://localhost:8082/user
    feed-service:
      path: /feed/**
      url: http://localhost:8081/feed
    posts-service:
      path: /post/**
      url: http://localhost:8083/post

endpoints:
  trace:
    sensitive: false

ribbon:
  eureka:
    enabled: false